version: "3.8"
services:
  db:
    image: postgres:15
    container_name: towtruck_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-tow_truck}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: .
    container_name: towtruck_backend
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASS: ${DB_PASS:-postgres}
      DB_NAME: ${DB_NAME:-tow_truck}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-dev_access_secret}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-dev_refresh_secret}
      BOT_TOKEN: ${BOT_TOKEN}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL:-admin@example.com}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD:-changeme}
    ports:
      - "3000:3000"
volumes:
  db_data:

